"""Add team_a_image and team_b_image to FootballMatch

Revision ID: 89839ae6798b
Revises: a858894e959b
Create Date: 2025-05-15 20:07:38.477106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89839ae6798b'
down_revision = 'a858894e959b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football_match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_a_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('team_b_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football_match', schema=None) as batch_op:
        batch_op.drop_column('team_b_image')
        batch_op.drop_column('team_a_image')

    # ### end Alembic commands ###
